name: movies_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^0.13.5
  pull_to_refresh: ^2.0.0
  sizer: ^2.0.15
  lottie: ^2.2.0
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  intl: ^0.18.0
  circular_menu: ^2.0.1


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
